[package]
name = "bmc-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bmc-core = { version = "*", path = "../bmc-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"
