[package]
name = "schema-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
schema-core = { version = "*", path = "../schema-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"
