[package]
name = "bmc-core"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
colored-diff = "0.2.3"

[dependencies]
shared = { version = "*", path = "../../shared" }
syn = { version = "1.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
